CATALOG = [
    {"title": "Inception", "tags": "sci-fi thriller dream mind-bending suspense Christopher-Nolan heist"},
    {"title": "The Dark Knight", "tags": "action thriller superhero dark gritty crime Christopher-Nolan Batman"},
    {"title": "Interstellar", "tags": "sci-fi space emotional time-travel epic Christopher-Nolan adventure"},
    {"title": "The Matrix", "tags": "sci-fi action cyberpunk mind-bending dystopian Keanu-Reeves virtual-reality"},
    {"title": "Pulp Fiction", "tags": "crime drama dark-comedy nonlinear cult-classic Tarantino witty"},
    {"title": "Forrest Gump", "tags": "drama heartwarming emotional historical life-story Tom-Hanks inspirational"},
    {"title": "The Shawshank Redemption", "tags": "drama prison friendship hope emotional inspirational classic"},
    {"title": "Toy Story", "tags": "animation comedy family heartwarming adventure Pixar buddy"},
    {"title": "Parasite", "tags": "thriller drama dark-comedy social-class suspense Korean foreign"},
    {"title": "La La Land", "tags": "romance musical emotional bittersweet dreamy jazz artistic"},
    {"title": "The Conjuring", "tags": "horror supernatural haunting paranormal suspense scary creepy"},
    {"title": "Mad Max: Fury Road", "tags": "action sci-fi post-apocalyptic adrenaline car-chase explosive visual"},
    {"title": "Get Out", "tags": "horror thriller social-commentary psychological suspense thought-provoking Jordan-Peele"},
    {"title": "The Grand Budapest Hotel", "tags": "comedy drama quirky visual artistic stylized Wes-Anderson colorful"},
    {"title": "Gladiator", "tags": "action drama historical epic revenge Roman Russell-Crowe brutal"},
    {"title": "Spirited Away", "tags": "animation fantasy adventure emotional Japanese Studio-Ghibli magical surreal"},
    {"title": "Fight Club", "tags": "drama thriller psychological mind-bending dark cult-classic Brad-Pitt"},
    {"title": "The Notebook", "tags": "romance drama emotional tearjerker love-story tragic Nicholas-Sparks"},
]
